# Generated by Django 4.0.4 on 2022-04-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_num', models.IntegerField(max_length=4, verbose_name='蔵書番号')),
                ('name', models.CharField(max_length=255, verbose_name='書籍名')),
                ('publisher', models.CharField(blank=True, max_length=255, verbose_name='出版社')),
                ('isavailable', models.BooleanField(default=True, verbose_name='貸出可否')),
            ],
        ),
    ]
