# Generated by Django 4.0.4 on 2022-04-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='renter',
            field=models.CharField(default='', max_length=64, verbose_name='借りている人'),
        ),
    ]
