# Generated by Django 3.2.5 on 2022-04-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_book_renter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_num',
            field=models.IntegerField(verbose_name='蔵書番号'),
        ),
    ]
