# Generated by Django 4.0.4 on 2022-04-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_book_renter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_num',
            field=models.IntegerField(unique=True, verbose_name='蔵書番号'),
        ),
    ]
